with-expecter: True
inpackage: True
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}_gen_test.go"

packages:
  github.com/aungmawjj/mypaste/mypaste:
    interfaces:
      IdTokenValidator:
