with-expecter: true
dir: "mocks"
outpkg: "mpmocks"
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}_gen.go"
packages:
  github.com/aungmawjj/my-paste/mypaste:
    interfaces:
      EchoContext:
      EchoLogger:
      IdTokenValidator:
      GoogleSignInValidator: