// Code generated by mockery v2.40.1. DO NOT EDIT.

package mpmocks

import (
	echo "github.com/labstack/echo/v4"
	idtoken "google.golang.org/api/idtoken"

	mock "github.com/stretchr/testify/mock"
)

// MockGoogleSignInValidator is an autogenerated mock type for the GoogleSignInValidator type
type MockGoogleSignInValidator struct {
	mock.Mock
}

type MockGoogleSignInValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoogleSignInValidator) EXPECT() *MockGoogleSignInValidator_Expecter {
	return &MockGoogleSignInValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: c
func (_m *MockGoogleSignInValidator) Validate(c echo.Context) (*idtoken.Payload, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *idtoken.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) (*idtoken.Payload, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) *idtoken.Payload); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idtoken.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoogleSignInValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockGoogleSignInValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockGoogleSignInValidator_Expecter) Validate(c interface{}) *MockGoogleSignInValidator_Validate_Call {
	return &MockGoogleSignInValidator_Validate_Call{Call: _e.mock.On("Validate", c)}
}

func (_c *MockGoogleSignInValidator_Validate_Call) Run(run func(c echo.Context)) *MockGoogleSignInValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockGoogleSignInValidator_Validate_Call) Return(_a0 *idtoken.Payload, _a1 error) *MockGoogleSignInValidator_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoogleSignInValidator_Validate_Call) RunAndReturn(run func(echo.Context) (*idtoken.Payload, error)) *MockGoogleSignInValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoogleSignInValidator creates a new instance of MockGoogleSignInValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoogleSignInValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoogleSignInValidator {
	mock := &MockGoogleSignInValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
