name: CI/CD

on:
  push:
    branches: 
      - master

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ vars.DOMAIN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/mypaste
          tags: type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.DOMAIN }} > ~/.ssh/known_hosts

      - name: Deploy image
        env:
          IMAGE: "${{ steps.meta.outputs.tags }}"
        run: |
          echo ${{ env.IMAGE }}
          ssh root@${{ env.DOMAIN }} "
            cd /opt/mypaste
            podman pull ${{ env.IMAGE }}
            podman stop mypaste
            podman rm mypaste
            podman run --name mypaste --env-file .env \
              --volume /opt/mypaste/tls-cache:/var/www/cache -p 80:80 -p 443:443 -d ${{ env.IMAGE }}
            podman image prune -af
          "
